name: flutter_1nep
description: A new Flutter application.

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.1
  provider: ^5.0.0
  pinput: ^1.2.0
  flutter_spinkit: ^5.0.0
  dots_indicator: ^2.0.0
  geolocator: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: bethellen
      fonts:
        - asset: fonts/BethEllen-Regular.ttf
